version: '3.8'

services:
  backend:
    build: ./backend
    container_name: taxlaw-backend
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JAVA_OPTS=-Xmx512m -Dspring.profiles.active=docker
    volumes:
      - ./logs:/app/logs
    networks:
      - taxlaw-network
    restart: unless-stopped

  # Placeholder for future RAG engine service
  rag-engine:
    image: alpine:latest
    container_name: taxlaw-rag-engine
    command: echo "RAG engine placeholder - to be implemented"
    ports:
      - "5000:5000"
    networks:
      - taxlaw-network
    restart: "no"

networks:
  taxlaw-network:
    driver: bridge
